import prisma from "../config/db.js";
import { generatePDF } from "../services/pdfGenerator.js";

export async function generateReport(req, res) {
  try {
    const match = await prisma.matchResult.findFirst({
      where: { id: req.params.matchId },
      include: {
        resume: true,
        jobDescription: true,
      },
    });
    if (!match) return res.status(404).json({ error: "Match not found" });

    const html = buildReportHTML(match);
    const pdfBuffer = await generatePDF(html);

    res.set({
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="resume-analysis-report.pdf"`,
    });
    res.send(pdfBuffer);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}

function buildReportHTML(match) {
  const skills = match.matchedSkills || [];
  const missing = match.missingSkills || [];
  const suggestions = match.suggestions || [];

  return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Resume Analysis Report</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
  h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
  .score { font-size: 48px; font-weight: bold; color: ${match.matchScore >= 70 ? "#16a34a" : match.matchScore >= 40 ? "#ca8a04" : "#dc2626"}; }
  .section { margin: 24px 0; }
  .section h2 { color: #1e293b; }
  ul { padding-left: 20px; }
  li { margin: 6px 0; }
  .skill { display: inline-block; background: #dbeafe; color: #1e40af; padding: 4px 12px; border-radius: 12px; margin: 4px; font-size: 14px; }
  .missing { background: #fce7f3; color: #9d174d; }
  .suggestion { background: #f0fdf4; color: #166534; padding: 12px; border-radius: 8px; margin: 8px 0; }
  .footer { margin-top: 40px; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
</style></head>
<body>
  <h1>Resume Analysis Report</h1>
  <p><strong>Resume:</strong> ${match.resume?.fileName || "N/A"}</p>
  <p><strong>Job:</strong> ${match.jobDescription?.title || "N/A"}</p>
  <div class="section">
    <h2>Match Score</h2>
    <div class="score">${match.matchScore}%</div>
  </div>
  <div class="section">
    <h2>Matched Skills (${skills.length})</h2>
    ${skills.map(s => `<span class="skill">${s}</span>`).join("") || "<p>None identified</p>"}
  </div>
  <div class="section">
    <h2>Missing Skills (${missing.length})</h2>
    ${missing.map(s => `<span class="skill missing">${s}</span>`).join("") || "<p>None identified</p>"}
  </div>
  <div class="section">
    <h2>Improvement Suggestions</h2>
    ${suggestions.map(s => `<div class="suggestion">${s}</div>`).join("") || "<p>No suggestions</p>"}
  </div>
  <div class="footer">Generated by AI Resume Analyzer</div>
</body></html>`;
}
